# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cli < Formula
  desc "A simple description of your application."
  homepage ""
  version "0.0.4"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/laurenzlong/cli/releases/download/v0.0.4/cli_Darwin_arm64.tar.gz"
      sha256 "6e5a3069d4057a8ac47ee6955efd29648f82c07f41d18b53773aaf19e54436bf"

      def install
        bin.install "amp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/laurenzlong/cli/releases/download/v0.0.4/cli_Darwin_x86_64.tar.gz"
      sha256 "2b3a8ab89420c545a3db09b3b161d0e9de2248f6c1ecfe672eaab018682c3de5"

      def install
        bin.install "amp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/laurenzlong/cli/releases/download/v0.0.4/cli_Linux_arm64.tar.gz"
      sha256 "6be140130b2a602029a6633dde41435a05bb07a8073162ff21aa458fd202e9bd"

      def install
        bin.install "amp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/laurenzlong/cli/releases/download/v0.0.4/cli_Linux_x86_64.tar.gz"
      sha256 "1b54549a9266ee3fe0529eb96b22de7a24ebf17d015c0fb2acdb0e324684360b"

      def install
        bin.install "amp"
      end
    end
  end
end
